name: Python CI  # Workflow'un adı

on:
  push:
    branches:
      - main  # Ana branch'e kod gönderildiğinde çalışır
  pull_request:
    branches:
      - main  # Pull request açıldığında çalışır

jobs:
  test:
    runs-on: ubuntu-latest  # İşletim sistemi: Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Depoyu klonla

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Python 3.9'u kur

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Gerekli kütüphaneleri yükle

    - name: Run tests
      run: |
        pytest src  # Testleri çalıştır
